-- SQL Schema for Supabase
-- Copy and paste this into the Supabase SQL Editor

-- Teams Table
CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT,
  leader_id BIGINT,
  description TEXT,
  photo TEXT,
  total_points INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  avatar TEXT,
  team_id BIGINT REFERENCES teams(id),
  points INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user',
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks Table
CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  points INTEGER DEFAULT 0,
  category TEXT,
  type TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_recurring TEXT,
  available_from TIMESTAMPTZ DEFAULT NOW(),
  deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Tasks Table
CREATE TABLE user_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  task_id BIGINT REFERENCES tasks(id),
  status TEXT DEFAULT 'pending',
  proof_url TEXT,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  verified_at TIMESTAMPTZ
);

-- Attendance Sessions Table
CREATE TABLE attendance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT,
  code TEXT UNIQUE,
  points INTEGER DEFAULT 10,
  is_active BOOLEAN DEFAULT TRUE,
  max_checkins INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Attendances Table
CREATE TABLE attendances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  session_id BIGINT REFERENCES attendance_sessions(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Biblical Questions Table
CREATE TABLE biblical_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  option_a TEXT,
  option_b TEXT,
  option_c TEXT,
  option_d TEXT,
  correct_option TEXT,
  category TEXT,
  difficulty TEXT,
  is_active BOOLEAN DEFAULT TRUE
);

-- Daily Quizzes Table
CREATE TABLE daily_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  date TEXT,
  score INTEGER
);

-- Tree Types Table
CREATE TABLE tree_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  rarity TEXT,
  max_stages INTEGER DEFAULT 6,
  points_per_stage INTEGER DEFAULT 5
);

-- User Trees Table
CREATE TABLE user_trees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  tree_type_id BIGINT REFERENCES tree_types(id),
  stage INTEGER DEFAULT 1,
  water_count INTEGER DEFAULT 0,
  last_watered_at TIMESTAMPTZ
);

-- App Settings Table
CREATE TABLE app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Functions for atomic point increments
CREATE OR REPLACE FUNCTION increment_user_points(row_id BIGINT, amount INT)
RETURNS void AS $$
BEGIN
  UPDATE users
  SET points = points + amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION increment_team_points(row_id BIGINT, amount INT)
RETURNS void AS $$
BEGIN
  UPDATE teams
  SET total_points = total_points + amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;
