-- SQL Schema for Supabase
-- Copy and paste this into the Supabase SQL Editor

-- Teams Table
CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT,
  leader_id BIGINT,
  description TEXT,
  photo TEXT,
  total_points INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  avatar TEXT,
  team_id BIGINT REFERENCES teams(id),
  points INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user',
  is_disabled BOOLEAN DEFAULT FALSE,
  birth_date DATE,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks Table
CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  points INTEGER DEFAULT 0,
  category TEXT,
  type TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_recurring TEXT,
  available_from TIMESTAMPTZ DEFAULT NOW(),
  deadline TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Tasks Table
CREATE TABLE user_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  task_id BIGINT REFERENCES tasks(id),
  status TEXT DEFAULT 'pending',
  proof_url TEXT,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  verified_at TIMESTAMPTZ
);

-- Attendance Sessions Table
CREATE TABLE attendance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT,
  code TEXT UNIQUE,
  points INTEGER DEFAULT 10,
  is_active BOOLEAN DEFAULT TRUE,
  max_checkins INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Attendances Table
CREATE TABLE attendances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  session_id BIGINT REFERENCES attendance_sessions(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Biblical Questions Table
CREATE TABLE biblical_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  option_a TEXT,
  option_b TEXT,
  option_c TEXT,
  option_d TEXT,
  correct_option TEXT,
  category TEXT,
  difficulty TEXT,
  is_active BOOLEAN DEFAULT TRUE
);

-- Daily Quizzes Table
CREATE TABLE daily_quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  date TEXT,
  score INTEGER
);

-- Tree Types Table
CREATE TABLE tree_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  rarity TEXT,
  max_stages INTEGER DEFAULT 6,
  points_per_stage INTEGER DEFAULT 5
);

-- User Trees Table
CREATE TABLE user_trees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  tree_type_id BIGINT REFERENCES tree_types(id),
  stage INTEGER DEFAULT 1,
  water_count INTEGER DEFAULT 0,
  last_watered_at TIMESTAMPTZ
);

-- App Settings Table
CREATE TABLE app_settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Bible Books Table
CREATE TABLE bible_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  order_index INTEGER DEFAULT 0,
  visible BOOLEAN DEFAULT TRUE,
  released BOOLEAN DEFAULT FALSE
);

-- Bible Chapters Table
CREATE TABLE bible_chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES bible_books(id),
  chapter_number INTEGER,
  title TEXT,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Game Plays Table
CREATE TABLE game_plays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  game_id TEXT,
  date TEXT,
  count INTEGER DEFAULT 0
);

-- User Bible Readings Table
CREATE TABLE user_bible_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  chapter_id BIGINT REFERENCES bible_chapters(id),
  read_at TEXT,
  points_awarded INTEGER DEFAULT 0
);

-- Birthday Messages Table
CREATE TABLE birthday_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  birthday_user_id BIGINT REFERENCES users(id),
  sender_user_id BIGINT REFERENCES users(id),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Birthday Events Table
CREATE TABLE birthday_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  admin_message TEXT,
  image_url TEXT,
  year INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Functions for atomic point increments
CREATE OR REPLACE FUNCTION increment_user_points(row_id BIGINT, amount INT)
RETURNS void AS $$
BEGIN
  UPDATE users
  SET points = points + amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION increment_team_points(row_id BIGINT, amount INT)
RETURNS void AS $$
BEGIN
  UPDATE teams
  SET total_points = total_points + amount
  WHERE id = row_id;
END;
$$ LANGUAGE plpgsql;

-- Investigation Cases Table
CREATE TABLE investigation_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  answer TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  reward_points INTEGER DEFAULT 100,
  max_attempts INTEGER,
  use_dynamic_scoring BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Investigation Clues Table
CREATE TABLE investigation_clues (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  clue_text TEXT NOT NULL,
  release_datetime TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Investigation Hints Table
CREATE TABLE investigation_hints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  hint_text TEXT NOT NULL,
  cost_points INTEGER DEFAULT 10,
  release_datetime TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Investigation Hint Purchases Table
CREATE TABLE investigation_hint_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hint_id UUID REFERENCES investigation_hints(id) ON DELETE CASCADE,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(hint_id, team_id)
);

-- Investigation Notifications Table
CREATE TABLE investigation_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  clue_id UUID REFERENCES investigation_clues(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Team Answers Table
CREATE TABLE team_answers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  answer_text TEXT NOT NULL,
  is_correct BOOLEAN DEFAULT FALSE,
  points_awarded INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Investigation Team Attempts Table
CREATE TABLE investigation_team_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  attempts_used INTEGER DEFAULT 0,
  is_eliminated BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(case_id, team_id)
);

-- Investigation Team Logs Table
CREATE TABLE investigation_team_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES investigation_cases(id) ON DELETE CASCADE,
  team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL, -- 'hint_purchase', 'answer_attempt', 'correct_answer', 'eliminated'
  description TEXT,
  points_spent INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
